controller_manager:
  ros__parameters:
    update_rate: 50
    use_joint_limits: true

    pinc_open_driver_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pinc_open_driver_position_controller:
      type: position_controllers/JointGroupPositionController

    pinc_open_driver_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

pinc_open_driver_joint_state_broadcaster:
  ros__parameters:
      joints:
        - gripper
      interfaces:
        - position
        - velocity

pinc_open_driver_position_controller:
  ros__parameters:
      joints:
        - gripper
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      joint_limits:
        gripper:
          has_position_limits: true
          min_position: -2.4   # fully open
          max_position: 0.0    # fully closed

pinc_open_driver_trajectory_controller:
  ros__parameters:
    joints:
      - gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05
      gripper:
        trajectory: 0.1  # max allowed trajectory error
        goal: 0.1         # max allowed goal error

