#!/usr/bin/env python3

# Copyright 2025 Christopher Newport University - CNU Robotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flash gripper firmware and test script."""

import time

from pypot.feetech import FeetechSTS3215IO


def open_gripper():
    gripper.enable_torque([ID])
    gripper.set_goal_position({ID: -140})


def close_gripper():
    gripper.enable_torque([ID])
    gripper.set_goal_position({ID: 0})


if __name__ == '__main__':

    # @TODO - make ID, PORT, and BAUD configurable
    ID = 6
    PORT = '/dev/tty'
    BAUD = '1000000'
    gripper = FeetechSTS3215IO(port=PORT, baudrate=BAUD)

    gripper.enable_torque([6])

    gripper.disable_torque([6])

    gripper.get_present_position([ID])

    gripper.set_lock({ID: 0})
    time.sleep(0.5)

    gripper.set_acceleration({ID: 200})
    time.sleep(0.5)

    gripper.set_max_angle_limit({ID: 0})
    time.sleep(0.5)

    gripper.set_min_angle_limit({ID: -147})
    time.sleep(0.5)

    gripper.set_torque_limit({ID: 1000})
    time.sleep(0.5)

    gripper.set_overload_torque({ID: 40})
    time.sleep(0.5)

    gripper.set_protective_torque({ID: 5})
    time.sleep(0.5)

    gripper.set_protection_time({ID: 7})
    time.sleep(0.5)

    gripper.set_lock({ID: 1})

    # open_gripper()
    # close_gripper()
